import{useEffect,useMemo,useRef,useState}from'react';import{presets}from'./data/presets';import{t}from'./i18n/strings';import{duplicateOptions,normaliseOptions,validateOptions}from'./lib/options';import{eliminateOne,generateTeams,randomInclusive,selectMultiple,selectOne,type Team}from'./lib/random';import{loadLists,saveLists,STORAGE_KEY,type SavedList}from'./lib/storage';import{winningRotation}from'./lib/wheel';
type Mode='one'|'multiple'|'eliminate'|'yesno'|'number'|'teams';
const modes:Record<Mode,string>={one:'Pick one',multiple:'Pick multiple',eliminate:'Elimination',yesno:'Yes or No',number:'Random number',teams:'Team generator'};
const palette=['#e05a2a','#087f73','#49348a','#c24163','#1474a4','#8a5a16','#63711d','#9b3f88'];
export default function App(){
 const[raw,setRaw]=useState('');const[mode,setMode]=useState<Mode>('one');const[count,setCount]=useState(2);const[min,setMin]=useState(1);const[max,setMax]=useState(10);const[teamRaw,setTeamRaw]=useState('Team Saffron\nTeam Indigo');const[result,setResult]=useState('');const[history,setHistory]=useState<string[]>([]);const[spinning,setSpinning]=useState(false);const[rotation,setRotation]=useState(0);const[winnerIndex,setWinnerIndex]=useState<number>();const[remaining,setRemaining]=useState<string[]>([]);const[roundMessage,setRoundMessage]=useState('');const[teams,setTeams]=useState<Team[]>([]);const[lists,setLists]=useState<SavedList[]>([]);const[storageError,setStorageError]=useState<string|null>(null);const[notice,setNotice]=useState('');const timer=useRef<ReturnType<typeof window.setTimeout>|undefined>(undefined);
 const options=useMemo(()=>normaliseOptions(raw.split('\n')),[raw]);const errors=mode==='number'||mode==='yesno'?[]:validateOptions(options);const duplicates=duplicateOptions(options);const reduced=useMemo(()=>matchMedia('(prefers-reduced-motion: reduce)').matches,[]);
 useEffect(()=>{const loaded=loadLists(localStorage);setLists(loaded.lists);setStorageError(loaded.error);return()=>clearTimeout(timer.current)},[]);
 const locked=spinning;const updateRaw=(value:string)=>{if(!locked){setRaw(value);setRemaining([]);setWinnerIndex(undefined)}};
 const announce=(value:string)=>{setResult(value);setHistory(h=>[value,...h].slice(0,10));};
 function finish(value:string,index?:number){setSpinning(false);setWinnerIndex(index);announce(value);if(navigator.vibrate)navigator.vibrate(35)}
 function choose(){if(spinning)return;if(mode==='number'){if(!Number.isSafeInteger(min)||!Number.isSafeInteger(max)||min>max){setNotice('Enter a valid whole-number range.');return}announce(String(randomInclusive(min,max)));return}if(mode==='yesno'){const value=selectOne(['Yes','No']);setSpinning(true);const i=value==='Yes'?0:1;setRotation(r=>winningRotation(i,2,r));timer.current=window.setTimeout(()=>finish(value,i),reduced?50:1800);return}if(errors.length)return;if(mode==='multiple'){if(count<1||count>options.length){setNotice('The count must fit the available choices.');return}announce(selectMultiple(options,count).join(', '));return}if(mode==='teams'){const names=normaliseOptions(teamRaw.split('\n'));if(names.length<2){setNotice('Add at least two team names.');return}const made=generateTeams(options,names);setTeams(made);announce(made.map(x=>`${x.name}: ${x.members.join(', ')}`).join(' | '));return}if(mode==='eliminate'){const pool=remaining.length?remaining:options;const round=eliminateOne(pool);setRemaining(round.remaining);setRoundMessage(`${round.selected} — ${t('removed')}.`);if(round.finished){announce(round.remaining[0]!);setRoundMessage(`${t('winner')}: ${round.remaining[0]}`)}return}const picked=selectOne(options);const index=options.indexOf(picked);setSpinning(true);setWinnerIndex(undefined);setRotation(r=>winningRotation(index,options.length,r));timer.current=window.setTimeout(()=>finish(picked,index),reduced?50:1800)}
 function clear(){if(options.length&& !confirm('Clear all choices?'))return;updateRaw('');setResult('')}
 function persist(next:SavedList[]){setLists(next);setStorageError(saveLists(localStorage,next))}
 function saveCurrent(){if(errors.length)return;const name=prompt('Name this list:')?.trim();if(!name)return;const existing=lists.find(x=>x.name.toLocaleLowerCase()===name.toLocaleLowerCase());if(existing&&!confirm(`Replace “${existing.name}”?`))return;persist(existing?lists.map(x=>x.id===existing.id?{...x,name,options}:x):[...lists,{id:crypto.randomUUID(),name,options}])}
 function renameList(list:SavedList){const name=prompt('Rename this list:',list.name)?.trim();if(name)persist(lists.map(x=>x.id===list.id?{...x,name}:x))}
 function deleteList(list:SavedList){if(confirm(`Delete “${list.name}”?`))persist(lists.filter(x=>x.id!==list.id))}
 async function copy(){try{await navigator.clipboard.writeText(result);setNotice('Result copied.')}catch{const area=document.createElement('textarea');area.value=result;document.body.append(area);area.select();document.execCommand('copy');area.remove();setNotice('Result copied.')}}
 async function share(){if(navigator.share)await navigator.share({title:t('brand'),text:result});else await copy()}
 const wheelOptions=mode==='yesno'?['Yes','No']:(remaining.length&&mode==='eliminate'?remaining:options);
 const gradient=wheelOptions.length?`conic-gradient(${wheelOptions.map((_,i)=>`${palette[i%palette.length]} ${i*360/wheelOptions.length}deg ${(i+1)*360/wheelOptions.length}deg`).join(',')})`:'#ddd';
 return <><header><div><p className="eyebrow">Decision picker</p><h1>{t('brand')}</h1><p>{t('tagline')}</p></div><span className="privacy">🔒 {t('privacy')}</span></header><main id="main"><section className="card controls" aria-labelledby="choices-title"><label>{t('mode')}<select value={mode} disabled={locked} onChange={e=>{setMode(e.target.value as Mode);setResult('');setTeams([])}}>{Object.entries(modes).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>
 {mode==='number'?<div className="row"><label>{t('min')}<input type="number" value={min} onChange={e=>setMin(e.target.valueAsNumber)}/></label><label>{t('max')}<input type="number" value={max} onChange={e=>setMax(e.target.valueAsNumber)}/></label></div>:mode!=='yesno'&&<><div className="section-head"><h2 id="choices-title">{t('choices')} <small>{options.length}</small></h2><div><button className="quiet" disabled={locked} onClick={()=>updateRaw(presets[0]!.options.join('\n'))}>{t('loadExample')}</button><button className="quiet danger" disabled={locked} onClick={clear}>{t('clearAll')}</button></div></div><label className="sr-only" htmlFor="choices">{t('pasteHint')}</label><textarea id="choices" rows={9} disabled={locked} value={raw} placeholder={'Masala dosa\nChole bhature\nMomos'} onChange={e=>updateRaw(e.target.value)}/><ul className="option-list" aria-label="Current choices">{options.map((option,index)=><li key={`${option}-${index}`}><span>{option}</span><button disabled={locked} aria-label={`Remove ${option}`} onClick={()=>updateRaw(options.filter((_,i)=>i!==index).join('\n'))}>×</button></li>)}</ul>{!options.length&&<p className="empty">✨ {t('empty')}</p>}{errors.length>0&&<div className="error" role="alert"><strong>{t('validation')}</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}{duplicates.length>0&&null}</>}
 {mode==='multiple'&&<label>{t('count')}<input type="number" min="1" max={options.length} value={count} onChange={e=>setCount(e.target.valueAsNumber)}/></label>}{mode==='teams'&&<label>{t('teams')}<textarea rows={3} value={teamRaw} onChange={e=>setTeamRaw(e.target.value)}/></label>}
 <button className="primary" disabled={spinning||((mode!=='number'&&mode!=='yesno')&&errors.length>0)} onClick={choose}>{spinning?t('spinning'):mode==='one'||mode==='yesno'?t('spin'):t('pick')}</button>{reduced&&<p className="hint">{t('reduced')}</p>}{mode==='eliminate'&&remaining.length>0&&<div><p><strong>{roundMessage}</strong></p><p>{t('remaining')}: {remaining.join(', ')}</p><button onClick={()=>{setRemaining([]);setRoundMessage('');setResult('')}}>{t('restart')}</button></div>}</section>
 <section className="card stage" aria-label="Selection wheel and result"><div className="wheel-wrap"><div className="pointer" aria-hidden="true">▼</div><div className={`wheel ${spinning?'is-spinning':''}`} style={{background:gradient,transform:`rotate(${rotation}deg)`,transitionDuration:reduced?'0.05s':'1.8s'}} aria-hidden="true">{wheelOptions.map((o,i)=><span key={`${o}-${i}`} className={winnerIndex===i?'winning':''} style={{transform:`rotate(${(i+.5)*360/wheelOptions.length}deg) translateY(-41%)`}}>{o.length>14?`${o.slice(0,13)}…`:o}</span>)}</div></div><div className="result" aria-live="polite" aria-atomic="true">{result&&<><p>{t('result')}</p><h2>★ {result}</h2><div className="row center"><button onClick={copy}>{t('copy')}</button><button onClick={share}>{t('share')}</button><button onClick={choose}>{t('again')}</button></div></>}{notice&&<p>{notice}</p>}</div>{teams.length>0&&<div className="team-grid">{teams.map(team=><article key={team.name}><h3>{team.name}</h3><ol>{team.members.map(x=><li key={x}>{x}</li>)}</ol></article>)}</div>}</section>
 <aside className="card library"><h2>{t('presets')}</h2><div className="chips">{presets.map(p=><button disabled={locked} key={p.name} onClick={()=>updateRaw(p.options.join('\n'))}>{p.name}</button>)}</div><hr/><h2>{t('saved')}</h2><p>{t('storageNote')}</p>{storageError&&<p className="error" role="alert">{storageError}</p>}<button onClick={saveCurrent}>{t('save')}</button>{lists.length===0?<p>{t('noSaved')}</p>:<ul className="saved">{lists.map(list=><li key={list.id}><strong>{list.name}</strong><span><button onClick={()=>updateRaw(list.options.join('\n'))}>{t('open')}</button><button onClick={()=>renameList(list)}>{t('rename')}</button><button onClick={()=>deleteList(list)}>{t('remove')}</button></span></li>)}</ul>}<button className="danger quiet" onClick={()=>{if(lists.length&&confirm('Clear all locally saved lists?')){localStorage.removeItem(STORAGE_KEY);setLists([])}}}>{t('clearSaved')}</button><hr/><h2>{t('history')}</h2>{history.length?<><ol>{history.map((h,i)=><li key={`${h}-${i}`}>{h}</li>)}</ol><button onClick={()=>setHistory([])}>{t('clearHistory')}</button></>:<p>No results this session.</p>}</aside></main><footer>Made for everyday indecision. Private by design.</footer></>}
